apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: shopstack-dev
  namespace: argocd

spec:
  description: full stack project

  sourceRepos:
    - https://github.com/yureshgurung/shopstack-gitops.git

  destinations:
    - server: https://10.10.10.8:6443
      namespace: shopstack-dev

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap

    - group: ""
      kind: Service

    - group: ""
      kind: ServiceAccount

    - group: apps
      kind: Deployment

    - group: autoscaling
      kind: HorizontalPodAutoscaler

    - group: policy
      kind: PodDisruptionBudget

    - group: networking.k8s.io
      kind: NetworkPolicy

    - group: gateway.networking.k8s.io
      kind: HTTPRoute