{{- if and .Values.frontend.enabled .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "shopstack.frontendName" . }}
  labels:
    {{- include "shopstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend

spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "shopstack.name" . }}
      app.kubernetes.io/component: frontend
{{- end }}