{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: {{ include "shopstack.fullname" . }}
  labels:
    {{- include "shopstack.labels" . | nindent 4 }}

spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}

  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  rules:
    # Backend API
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.httpRoute.backendPath }}

      backendRefs:
        - name: {{ include "shopstack.fullname" . }}-backend
          port: {{ .Values.backend.service.port }}
          weight: 1

    # Frontend
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.httpRoute.frontendPath }}

      backendRefs:
        - name: {{ include "shopstack.fullname" . }}-frontend
          port: {{ .Values.frontend.service.port }}
          weight: 1
{{- end }}